### ISSUE TITLE
小米手机插上摄像头，然后直接拔掉摄像头，app崩溃bug

### ISSUE THREAD

**Issue by qwinner** [Liuguihong/AndroidUVCCamera#4]
在一些手机上，直接拔掉摄像头，会提示拔掉，不会崩溃。但是有些手机出现那个问题，不知道有没有人遇到过，如何解决的？谢谢

**Comment by Liuguihong** [comment]
可以把log贴出来看下

**Comment by qwinner** [comment]
已经解决了，是so包的问题，网上有人给我一个修改后的so包更换就好了。谢谢

**Comment by mafanwei** [comment]
我也想要这个so包···
